/*global javascripture*/
var hebrew = {
	stripPointing: function( word ) {
		return word.replace(/֑/gi,'')
		.replace(/֓/gi,'')
		.replace(/֕/gi,'')
		.replace(/֖/gi,'')
		.replace(/֘/gi,'')
		.replace(/֙/gi,'')
		.replace(/֚/gi,'')
		.replace(/֛/gi,'')
		.replace(/֜/gi,'')
		.replace(/֝/gi,'')
		.replace(/֞/gi,'')
		.replace(/֟/gi,'')
		.replace(/֠/gi,'')
		.replace(/֡/gi,'')
		.replace(/֢/gi,'')
		.replace(/֣/gi,'')
		.replace(/֤/gi,'')
		.replace(/֥/gi,'')
		.replace(/֦/gi,'')
		.replace(/֧/gi,'')
		.replace(/֩/gi,'')
		.replace(/֪/gi,'')
		.replace(/֫/gi,'')
		.replace(/֬/gi,'')
		.replace(/֭/gi,'')
		.replace(/֮/gi,'')
		.replace(/֯/gi,'')
		.replace(/ֱ/gi,'')
		.replace(/ֲ/gi,'')
		.replace(/ֳ/gi,'')
		.replace(/ֵ/gi,'')
		.replace(/ֶ/gi,'')
		.replace(/ַ/gi,'')
		.replace(/ָ/gi,'')
		.replace(/ֹ/gi,'')
		.replace(/ֺ/gi,'')
		.replace(/ֻ/gi,'')
		.replace(/ּ/gi,'')
		.replace(/ֽ/gi,'')
		.replace(/־/gi,'')
		.replace(/׀/gi,'')
		.replace(/ׂ/gi,'')
		.replace(/׃/gi,'')
		.replace(/ׄ/gi,'')
		.replace(/ׇ/gi,'')
		.replace(/ׁ/gi,'')
		.replace(/ִ/gi,'')
		.replace(/ְ/,'')
		//new ones
		.replace(/ְ/,'')
		.replace(/ְ/,'')
		.replace(/ְ/,'')
		.replace(/֗/,'')
		.replace(/ְ/,'')
		.replace(/ְ/,'')
		.replace(/֔/,'')
		.replace(/ְ/,'')
		.replace(/ְ/,'')
		.replace(/֨/,'')
		.replace(/֑/,'')
		.replace(/֗/,'')
		.replace(/֨/,'')
		.replace(/֔/,'');
		//.replace(/\//,'');
	}
};

module.exports = hebrew;